import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "./Footer";
import NavComp from "./NavComp";
import Header from "./Header";
import Secoundcomp from "./Secoundcomp";
import ThirdComp from "./ThirdComp";
import Teammember from "./Teammember";
import FifthComp from "./FifthComp";
import ClientsFeedback from "./ClientsFeedback";
import OurBlogcomp from "./OurBlogcomp";
import ContactUs from "./ContactUS";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NavComp></NavComp>
      </div>
      <div>
        <Header></Header>
      </div>
      <div>
        <Secoundcomp></Secoundcomp>
      </div>
      <div>
        <ThirdComp />
      </div>
      <div>
        <Teammember></Teammember>
      </div>
      <div>
        <FifthComp></FifthComp>
      </div>
      <div>
        <ClientsFeedback></ClientsFeedback>
      </div>
      <div>
        <OurBlogcomp></OurBlogcomp>
      </div>
      <div>
        <ContactUs></ContactUs>
      </div>
      <div>
        <Footer></Footer>
      </div>
    </div>
  );
}
