import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "../component/Footer";
import NavComp from "../component/NavComp";
import Banner from "../component/Banner";
import AboutUs from "../component/AboutUs";
import OurExperiance from "../component/OurExperiance";
import Teammember from "../component/Teammember";
import OurWork from "../component/OurWork";
import ClientsFeedback from "../component/ClientsFeedback";
import OurBlogcomp from "../component/OurBlogcomp";
import ContactUs from "../component/ContactUS";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NavComp></NavComp>
      </div>
      
      <div>
        <Banner />
      </div>
      <div>
        <AboutUs />
      </div>
      <div>
        <OurExperiance />
      </div>
      <div>
        <Teammember></Teammember>
      </div>
      <div>
        <OurWork />
      </div>
      <div>
        <ClientsFeedback></ClientsFeedback>
      </div>
      <div>
        <OurBlogcomp></OurBlogcomp>
      </div>
      <div>
        <ContactUs></ContactUs>
      </div>
      <div>
        <Footer></Footer>
      </div>
    </div>
  );
}
